//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace DotNet
{
    using System;
    using System.Collections.Generic;

    [DataContract(IsReference = true)]
    public partial class Ticket
    {
        [DataMember]
        public int TicketId { get; set; }
        [DataMember]
        public System.DateTime DateTime { get; set; }
        [DataMember]
        public short Price { get; set; }
        [DataMember]
        public int MovieMovieId { get; set; }
        [DataMember]
        public int CinemaCinemaId { get; set; }
        [DataMember]
        public virtual Movie Movie { get; set; }
        [DataMember]
        public virtual Cinema Cinema { get; set; }
    }
}
